# Generated by Django 5.2.4 on 2025-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[("Frontend", "Frontend"), ("Backend", "Backend")],
                max_length=50,
            ),
        ),
    ]
